# Generated by Django 4.0.3 on 2022-08-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_alter_newword_options_remove_newword_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newword',
            name='is_added',
            field=models.BooleanField(default=False),
        ),
    ]
