# Generated by Django 4.0.3 on 2022-08-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('words', '0004_newword_is_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmanager',
            name='used_for',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
