# Generated by Django 4.0.3 on 2022-08-17 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_alter_linkmanager_used_for'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='video',
            new_name='video1',
        ),
    ]
