# Generated by Django 4.0.3 on 2022-10-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_rename_video_word_video1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='video1',
            new_name='video',
        ),
    ]
