# Generated by Django 4.0.3 on 2022-10-17 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0008_rename_video1_word_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='video',
            new_name='video1',
        ),
    ]
