# Generated by Django 4.0.3 on 2022-10-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('words', '0009_rename_video_word_video1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_word', models.IntegerField()),
                ('end_word', models.IntegerField()),
            ],
        ),
    ]
