# Generated by Django 4.0.3 on 2022-10-17 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0010_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmanager',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='words.word'),
        ),
    ]
