# Generated by Django 4.0.3 on 2022-10-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0012_alter_linkmanager_word'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newword',
            options={'verbose_name': 'کلمه جدید', 'verbose_name_plural': 'کلمات جدید'},
        ),
    ]
