# Generated by Django 4.0.3 on 2022-07-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_profetional',
            field=models.BooleanField(default=False),
        ),
    ]
