# Generated by Django 4.0.3 on 2022-07-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kernel', '0003_customuser_is_profetional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
    ]
