# Generated by Django 4.0.3 on 2022-10-17 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('kernel', '0005_facture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_profetional',
            new_name='is_professional',
        ),
    ]
