# Generated by Django 4.0.3 on 2022-10-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('words', '0012_alter_linkmanager_word'),
        ('affairs', '0001_initial'),
        ('kernel', '0007_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked_affair',
            field=models.ManyToManyField(related_name='like', to='affairs.affair'),
        ),
        migrations.AlterField(
            model_name='like',
            name='liked_words',
            field=models.ManyToManyField(related_name='like', to='words.word'),
        ),
    ]
