# Generated by Django 4.0.3 on 2022-10-27 08:27

from django.db import migrations
import kernel.models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0008_alter_like_liked_affair_alter_like_liked_words'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', kernel.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
    ]
