# Generated by Django 4.0.3 on 2022-07-31 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffairCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(blank=True, null=True, upload_to='media/icon/')),
                ('sort_id', models.IntegerField(blank=True, null=True)),
                ('farsi_name', models.CharField(blank=True, max_length=50, null=True)),
                ('english_name', models.CharField(blank=True, max_length=50, null=True)),
                ('arabic_name', models.CharField(blank=True, max_length=50, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             to='affairs.affaircategory')),
            ],
        ),
        migrations.CreateModel(
            name='Affair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farsi_description', models.CharField(blank=True, max_length=256, null=True)),
                ('english_description', models.CharField(blank=True, max_length=256, null=True)),
                ('arabic_description', models.CharField(blank=True, max_length=256, null=True)),
                ('sort_id', models.IntegerField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='media/videos/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               to='affairs.affaircategory')),
            ],
        ),
    ]
