# Generated by Django 4.0.3 on 2022-03-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affair',
            name='arabic_description2',
        ),
        migrations.RemoveField(
            model_name='affair',
            name='arabic_name',
        ),
        migrations.RemoveField(
            model_name='affair',
            name='english_description2',
        ),
        migrations.RemoveField(
            model_name='affair',
            name='english_name',
        ),
        migrations.RemoveField(
            model_name='affair',
            name='farsi_description2',
        ),
        migrations.RemoveField(
            model_name='affair',
            name='farsi_name',
        ),
    ]
