# Generated by Django 4.0.3 on 2022-10-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0002_affairlinkmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affairlinkmanager',
            name='affair',
        ),
    ]
