# Generated by Django 4.0.3 on 2022-10-28 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0003_remove_affairlinkmanager_affair'),
    ]

    operations = [
        migrations.AddField(
            model_name='affairlinkmanager',
            name='affair',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='video_link', to='affairs.affair'),
            preserve_default=False,
        ),
    ]
